"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft

from conftest import wait_for_dispatch_records

# =============================================================================
# Feature: F5 — Dispatch Records
# ID: f5-dispatch-records
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="f5-dispatch-records",
    scenario_id="records-returned-newest-first",
)
def test_records_returned_newest_first(client):
    """Records returned newest first

    Priority: high
    """
    with specleft.step(
        "Given two events that triggered the same rule at different times"
    ):
        payload = {
            "name": "record-order",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]
        client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )
        client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )

    with specleft.step(f"When I GET /dispatch-records?rule_id={id}"):
        records = wait_for_dispatch_records(client, rule_id, expected=2)

    with specleft.step("Then the more recent record appears first"):
        assert len(records) >= 2
        assert records[0]["dispatched_at"] >= records[1]["dispatched_at"]
