"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft

from conftest import assert_no_dispatch_records

# =============================================================================
# Feature: F2 — Conditions
# ID: f2-conditions
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="f2-conditions",
    scenario_id="gt-on-non-numeric-evaluates-false",
)
def test_gt_on_non_numeric_evaluates_false(client):
    """gt on non-numeric evaluates false

    Priority: high
    """
    with specleft.step('Given a rule with condition "user.role" gt "5"'):
        payload = {
            "name": "gt-non-numeric",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "gt", "value": "5"}],
            "channels": [{"type": "log", "config": {}}],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]

    with specleft.step('When I POST an event with payload {"user": {"role": "admin"}}'):
        event_response = client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )

    with specleft.step("Then the rule is not triggered"):
        assert event_response.status_code == 202
        assert payload["name"] not in event_response.json()["triggered_rules"]
        assert_no_dispatch_records(client, rule_id)


@specleft(
    feature_id="f2-conditions",
    scenario_id="missing-field-path-evaluates-false",
)
def test_missing_field_path_evaluates_false(client):
    """Missing field path evaluates false

    Priority: high
    """
    with specleft.step('Given a rule with condition "user.role" eq "admin"'):
        payload = {
            "name": "missing-field",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]

    with specleft.step('When I POST an event with payload missing "user.role"'):
        event_response = client.post(
            "/events", json={"type": "user.created", "payload": {"user": {}}}
        )

    with specleft.step("Then the rule is not triggered"):
        assert event_response.status_code == 202
        assert payload["name"] not in event_response.json()["triggered_rules"]
        assert_no_dispatch_records(client, rule_id)


@specleft(
    feature_id="f2-conditions",
    scenario_id="reject-unknown-operator",
)
def test_reject_unknown_operator(client):
    """Reject unknown operator

    Priority: high
    """
    with specleft.step(
        'Given a rule payload with a condition using operator "between"'
    ):
        payload = {
            "name": "invalid-operator",
            "event_type": "user.created",
            "conditions": [
                {"field": "user.role", "operator": "between", "value": "admin"}
            ],
            "channels": [{"type": "log", "config": {}}],
        }

    with specleft.step("When I POST to /rules"):
        response = client.post("/rules", json=payload)

    with specleft.step("Then I receive 422"):
        assert response.status_code == 422
