"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft

from conftest import wait_for_dispatch_records

# =============================================================================
# Feature: F3 — Channels
# ID: f3-channels
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="f3-channels",
    scenario_id="one-channel-failure-does-not-block-others",
)
def test_one_channel_failure_does_not_block_others(client):
    """One channel failure does not block others

    Priority: high
    """
    with specleft.step("Given a rule with a failing webhook channel and a log channel"):
        payload = {
            "name": "multi-channel",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [
                {"type": "webhook", "config": {"url": "https://fail.example.com"}},
                {"type": "log", "config": {}},
            ],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]

    with specleft.step("When the rule fires"):
        event_response = client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )

    with specleft.step("Then the log channel dispatches successfully"):
        assert event_response.status_code == 202
        records = wait_for_dispatch_records(client, rule_id, expected=2)
        statuses = {(record["channel_type"], record["status"]) for record in records}
        assert ("log", "sent") in statuses

    with specleft.step(
        'And a DispatchRecord with status "failed" exists for the webhook'
    ):
        assert ("webhook", "failed") in statuses


@specleft(
    feature_id="f3-channels",
    scenario_id="reject-invalid-email-config",
)
def test_reject_invalid_email_config(client):
    """Reject invalid email config

    Priority: high
    """
    with specleft.step("Given a rule payload with an email channel missing to"):
        payload = {
            "name": "invalid-email",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "email", "config": {}}],
        }

    with specleft.step("When I POST to /rules"):
        response = client.post("/rules", json=payload)

    with specleft.step("Then I receive 422"):
        assert response.status_code == 422


@specleft(
    feature_id="f3-channels",
    scenario_id="reject-invalid-webhook-config",
)
def test_reject_invalid_webhook_config(client):
    """Reject invalid webhook config

    Priority: high
    """
    with specleft.step("Given a rule payload with a webhook channel missing url"):
        payload = {
            "name": "invalid-webhook",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "webhook", "config": {}}],
        }

    with specleft.step("When I POST to /rules"):
        response = client.post("/rules", json=payload)

    with specleft.step("Then I receive 422"):
        assert response.status_code == 422
