"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

import time

from specleft import specleft

from conftest import assert_no_dispatch_records, wait_for_dispatch_records

# =============================================================================
# Feature: F4 — Event Publishing
# ID: f4-event-publishing
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="f4-event-publishing",
    scenario_id="event-response-is-non-blocking",
)
def test_event_response_is_non_blocking(client):
    """Event response is non-blocking

    Priority: medium
    """
    with specleft.step("Given a rule with a slow webhook channel"):
        payload = {
            "name": "slow-webhook",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [
                {"type": "webhook", "config": {"url": "https://slow.example.com"}}
            ],
        }
        client.post("/rules", json=payload)

    with specleft.step("When I POST a matching event"):
        start = time.monotonic()
        event_response = client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )
        elapsed = time.monotonic() - start

    with specleft.step("Then the response returns 202 before the webhook completes"):
        assert event_response.status_code == 202
        assert elapsed < 0.2


@specleft(
    feature_id="f4-event-publishing",
    scenario_id="inactive-rule-is-skipped",
)
def test_inactive_rule_is_skipped(client):
    """Inactive rule is skipped

    Priority: high
    """
    with specleft.step("Given a deactivated rule matching the event type"):
        payload = {
            "name": "inactive-rule",
            "event_type": "user.created",
            "is_active": False,
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]

    with specleft.step("When I POST a matching event"):
        event_response = client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )

    with specleft.step("Then the rule is not triggered"):
        assert event_response.status_code == 202
        assert payload["name"] not in event_response.json()["triggered_rules"]
        assert_no_dispatch_records(client, rule_id)


@specleft(
    feature_id="f4-event-publishing",
    scenario_id="only-matching-event-type-rules-evaluated",
)
def test_only_matching_event_type_rules_evaluated(client):
    """Only matching event_type rules evaluated

    Priority: medium
    """
    with specleft.step('Given a rule listening for event_type "order.created"'):
        payload = {
            "name": "order-rule",
            "event_type": "order.created",
            "conditions": [{"field": "order.total", "operator": "gt", "value": "10"}],
            "channels": [{"type": "log", "config": {}}],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]

    with specleft.step('When I POST an event with type "user.created"'):
        event_response = client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )

    with specleft.step("Then the rule is not triggered"):
        assert event_response.status_code == 202
        assert payload["name"] not in event_response.json()["triggered_rules"]
        assert_no_dispatch_records(client, rule_id)


@specleft(
    feature_id="f4-event-publishing",
    scenario_id="rule-does-not-fire-when-a-condition-fails",
)
def test_rule_does_not_fire_when_a_condition_fails(client):
    """Rule does not fire when a condition fails

    Priority: high
    """
    with specleft.step("Given the same rule"):
        payload = {
            "name": "role-admin",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]

    with specleft.step(
        'When I POST an event with payload {"user": {"role": "member"}}'
    ):
        event_response = client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "member"}}},
        )

    with specleft.step("Then no DispatchRecord is created for that rule"):
        assert event_response.status_code == 202
        assert_no_dispatch_records(client, rule_id)


@specleft(
    feature_id="f4-event-publishing",
    scenario_id="rule-fires-when-all-conditions-match",
)
def test_rule_fires_when_all_conditions_match(client):
    """Rule fires when all conditions match

    Priority: high
    """
    with specleft.step(
        'Given a rule with event_type "user.created" and condition user.role eq "admin"'
    ):
        payload = {
            "name": "admin-rule",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        rule_response = client.post("/rules", json=payload)
        rule_id = rule_response.json()["id"]

    with specleft.step(
        'When I POST an event {"type": "user.created", "payload": {"user": {"role": "admin"}}}'
    ):
        event_response = client.post(
            "/events",
            json={"type": "user.created", "payload": {"user": {"role": "admin"}}},
        )

    with specleft.step(
        'Then the rule is triggered and a DispatchRecord with status "sent" is created'
    ):
        assert event_response.status_code == 202
        assert payload["name"] in event_response.json()["triggered_rules"]
        records = wait_for_dispatch_records(client, rule_id, expected=1)
        assert len(records) == 1
        assert records[0]["status"] == "sent"
