"""
Auto-generated skeleton tests from Markdown specs.
Regenerate using: specleft test skeleton

Generated by SpecLeft - https://github.com/SpecLeft/specleft
"""

from specleft import specleft
from sqlalchemy import text

# =============================================================================
# Feature: F1 — Rule Management (CRUD)
# ID: f1-rule-management-crud
# =============================================================================

# Story: Default
# ID: default


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="create-a-valid-rule",
)
def test_create_a_valid_rule(client):
    """Create a valid rule

    Priority: high
    """
    with specleft.step("Given a rule payload with one condition and one log channel"):
        payload = {
            "name": "alert-on-signup",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }

    with specleft.step("When I POST to /rules"):
        response = client.post("/rules", json=payload)

    with specleft.step("Then I receive 201 with the created rule and its id"):
        assert response.status_code == 201
        data = response.json()
        assert data["id"]
        assert data["name"] == payload["name"]
        assert data["event_type"] == payload["event_type"]


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="delete-cascades-to-conditions-and-channels",
)
def test_delete_cascades_to_conditions_and_channels(client, db_session):
    """Delete cascades to conditions and channels

    Priority: high
    """
    with specleft.step("Given an existing rule with two conditions and one channel"):
        payload = {
            "name": "cascade-rule",
            "event_type": "user.created",
            "conditions": [
                {"field": "user.role", "operator": "eq", "value": "admin"},
                {"field": "user.id", "operator": "neq", "value": "0"},
            ],
            "channels": [{"type": "log", "config": {}}],
        }
        create_response = client.post("/rules", json=payload)
        rule_id = create_response.json()["id"]

    with specleft.step("When I DELETE the rule"):
        response = client.delete(f"/rules/{rule_id}")

    with specleft.step("Then the conditions and channel are also removed"):
        assert response.status_code == 204
        condition_count = db_session.execute(
            text("select count(*) from conditions")
        ).scalar()
        channel_count = db_session.execute(
            text("select count(*) from channels")
        ).scalar()
        assert condition_count == 0
        assert channel_count == 0


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="get-rule-by-id",
)
def test_get_rule_by_id(client):
    """Get rule by id

    Priority: medium
    """
    with specleft.step("Given an existing rule"):
        payload = {
            "name": "get-rule",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        create_response = client.post("/rules", json=payload)
        rule_id = create_response.json()["id"]

    with specleft.step(f"When I GET /rules/{id}"):
        response = client.get(f"/rules/{rule_id}")

    with specleft.step("Then I receive 200 with the rule"):
        assert response.status_code == 200
        data = response.json()
        assert data["id"] == rule_id
        assert data["name"] == payload["name"]


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="list-rules",
)
def test_list_rules(client):
    """List rules

    Priority: medium
    """
    with specleft.step("Given two existing rules"):
        payload_one = {
            "name": "list-rule-one",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        payload_two = {
            "name": "list-rule-two",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "member"}],
            "channels": [{"type": "log", "config": {}}],
        }
        client.post("/rules", json=payload_one)
        client.post("/rules", json=payload_two)

    with specleft.step("When I GET /rules"):
        response = client.get("/rules")

    with specleft.step("Then I receive 200 with both rules"):
        assert response.status_code == 200
        data = response.json()
        names = {item["name"] for item in data}
        assert {payload_one["name"], payload_two["name"]}.issubset(names)


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="reject-duplicate-rule-name",
)
def test_reject_duplicate_rule_name(client):
    """Reject duplicate rule name

    Priority: high
    """
    with specleft.step('Given an existing rule named "alert-on-signup"'):
        payload = {
            "name": "alert-on-signup",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        client.post("/rules", json=payload)

    with specleft.step('When I POST a new rule with name "alert-on-signup"'):
        response = client.post("/rules", json=payload)

    with specleft.step("Then I receive 409 Conflict"):
        assert response.status_code == 409


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="rule-creation-rejected-without-a-channel",
)
def test_rule_creation_rejected_without_a_channel(client):
    """Rule creation rejected without a channel

    Priority: high
    """
    with specleft.step("Given a rule payload with one condition and no channels"):
        payload = {
            "name": "missing-channel",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [],
        }

    with specleft.step("When I POST to /rules"):
        response = client.post("/rules", json=payload)

    with specleft.step("Then I receive 422"):
        assert response.status_code == 422


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="rule-creation-rejected-without-a-condition",
)
def test_rule_creation_rejected_without_a_condition(client):
    """Rule creation rejected without a condition

    Priority: high
    """
    with specleft.step("Given a rule payload with no conditions and one log channel"):
        payload = {
            "name": "missing-condition",
            "event_type": "user.created",
            "conditions": [],
            "channels": [{"type": "log", "config": {}}],
        }

    with specleft.step("When I POST to /rules"):
        response = client.post("/rules", json=payload)

    with specleft.step("Then I receive 422"):
        assert response.status_code == 422


@specleft(
    feature_id="f1-rule-management-crud",
    scenario_id="update-rule-fields",
)
def test_update_rule_fields(client):
    """Update rule fields

    Priority: medium
    """
    with specleft.step("Given an existing rule"):
        payload = {
            "name": "update-rule",
            "event_type": "user.created",
            "conditions": [{"field": "user.role", "operator": "eq", "value": "admin"}],
            "channels": [{"type": "log", "config": {}}],
        }
        create_response = client.post("/rules", json=payload)
        rule_id = create_response.json()["id"]

    with specleft.step(f"When I PATCH /rules/{id} with a new name and is_active false"):
        response = client.patch(
            f"/rules/{rule_id}", json={"name": "updated-rule", "is_active": False}
        )

    with specleft.step("Then I receive 200 with the updated rule"):
        assert response.status_code == 200
        data = response.json()
        assert data["name"] == "updated-rule"
        assert data["is_active"] is False
